{
  "language": "php",
  "php": 7.1.1,
  "sudo": false,
  "install": [
    "composer self-update",
    "composer install --prefer-dist"
  ],
  "before_script": [
    "phpenv rehash",
    "set +H"
  ],
  "script": [
    "sh -c \"if [ '$DEFAULT' = '1' ]; then phpunit --stderr; fi\"",
    "sh -c \"if [ '$PHPCS' = '1' ]; then ./vendor/bin/phpcs -n -p --extensions=php --standard=vendor/cakephp/cakephp-codesniffer/CakePHP ./src ./tests; fi\"",
    "sh -c \"if [ '$CODECOVERAGE' = '1' ]; then phpdbg -qrr vendor/bin/phpunit --coverage-clover=clover.xml || true; fi\""
  ],
  "after_success": [
    "bash <(curl -s https://codecov.io/bash)"
  ],
  "global_env": "DEFAULT=1",
  "group": "stable",
  "dist": "precise",
  "os": "linux"
}
