language: "php"

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

before_script: 
- "composer install"

script: 
- "php phpunit-6.4.3.phar 
C:\xampp\htdocs\cake-auth\tests\TestCase\Controller\UsersControllerTest.php --coverage-text --coverage-clover build/logs/clover.xml"

 


