language: php

php: 
  -7.1.1
  
sudo: false

install: 
    -composer self-update
    -composer install --prefer-dist
 
  
before_script: composer install
  
script: php phpunit-6.4.3.phar evacsystem/tests/TestCase/Controller/UsersControllerTest.php
    
after_success: bash <(curl -s https://codecov.io/bash)
  

 

